package org.confluence.mod.common.init.item;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.RegistryObject;
import org.confluence.mod.Confluence;
import org.confluence.mod.common.init.entity.BossEntities;
import org.confluence.mod.common.init.entity.CritterEntities;
import org.confluence.mod.common.init.entity.MonsterEntities;
import org.confluence.mod.common.init.entity.NpcEntities;
import org.mesdag.portlib.registries.PortDeferredItem;
import org.mesdag.portlib.registries.PortItemRegistration;
import org.mesdag.portlib.registries.PortRegisterHandler;

public final class SpawnEggItems {
    public static final PortItemRegistration ITEMS = PortRegisterHandler.item(Confluence.MODID);

    public static final PortDeferredItem<ForgeSpawnEggItem> SLIMELING_SPAWN_EGG = register(MonsterEntities.SLIMELING);
    public static final PortDeferredItem<ForgeSpawnEggItem> ENCHANTED_SWORD_SPAWN_EGG = register(MonsterEntities.ENCHANTED_SWORD);
    public static final PortDeferredItem<ForgeSpawnEggItem> BASE_BONES_SPAWN_EGG = register(MonsterEntities.BASE_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> GIANT_FLYING_FOX_SPAWN_EGG = register(MonsterEntities.GIANT_FLYING_FOX);
    public static final PortDeferredItem<ForgeSpawnEggItem> DRIPPLER_SPAWN_EGG = register(MonsterEntities.DRIPPLER);
    public static final PortDeferredItem<ForgeSpawnEggItem> GHOST_SPAWN_EGG = register(MonsterEntities.GHOST);
    public static final PortDeferredItem<ForgeSpawnEggItem> DUNGEON_SPIRIT_SPAWN_EGG = register(MonsterEntities.DUNGEON_SPIRIT);
    public static final PortDeferredItem<ForgeSpawnEggItem> CRIMSLIME_SPAWN_EGG = register(MonsterEntities.CRIMSLIME, 0x8B4949, 0x7D1D1D);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLOOD_CRAWLER_SPAWN_EGG = register(MonsterEntities.BLOOD_CRAWLER);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLOODY_SPORE_SPAWN_EGG = register(MonsterEntities.BLOODY_SPORE);
    public static final PortDeferredItem<ForgeSpawnEggItem> CRIMERA_SPAWN_EGG = register(MonsterEntities.CRIMERA);
    public static final PortDeferredItem<ForgeSpawnEggItem> HERPLING_SPAWN_EGG = register(MonsterEntities.HERPLING);
    public static final PortDeferredItem<ForgeSpawnEggItem> FACE_MONSTER_SPAWN_EGG = register(MonsterEntities.FACE_MONSTER);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLOOD_ZOMBIE_SPAWN_EGG = register(MonsterEntities.BLOOD_ZOMBIE);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLOOD_TUMORS_SPAWN_EGG = register(MonsterEntities.BLOOD_TUMORS);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLOOD_FEEDER_SPAWN_EGG = register(MonsterEntities.BLOOD_FEEDER);
    public static final PortDeferredItem<ForgeSpawnEggItem> FLESH_SLIME_SPAWN_EGG = register(MonsterEntities.FLESH_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> CORRUPT_SLIME_SPAWN_EGG = register(MonsterEntities.CORRUPT_SLIME, 0x3f3885, 0x625b9f);
    public static final PortDeferredItem<ForgeSpawnEggItem> EATER_OF_SOULS_SPAWN_EGG = register(MonsterEntities.EATER_OF_SOULS);
    public static final PortDeferredItem<ForgeSpawnEggItem> DEVOURER_SPAWN_EGG = register(MonsterEntities.DEVOURER);
    public static final PortDeferredItem<ForgeSpawnEggItem> WORLD_FEEDER_SPAWN_EGG = register(MonsterEntities.WORLD_FEEDER);
    public static final PortDeferredItem<ForgeSpawnEggItem> DECAYEDER_SPAWN_EGG = register(MonsterEntities.DECAYEDER);
    public static final PortDeferredItem<ForgeSpawnEggItem> CORRUPTOR_SPAWN_EGG = register(MonsterEntities.CORRUPTOR);
    public static final PortDeferredItem<ForgeSpawnEggItem> SLIMER_SPAWN_EGG = register(MonsterEntities.SLIMER);
    public static final PortDeferredItem<ForgeSpawnEggItem> LUMINOUS_SLIME_SPAWN_EGG = register(MonsterEntities.LUMINOUS_SLIME, 0xFF00FF, 0xEDFFFA);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIXIE_SPAWN_EGG = register(MonsterEntities.PIXIE);
    public static final PortDeferredItem<ForgeSpawnEggItem> UNICORN_SPAWN_EGG = register(MonsterEntities.UNICORN);
    public static final PortDeferredItem<ForgeSpawnEggItem> GASTROPOD_SPAWN_EGG = register(MonsterEntities.GASTROPOD);
    public static final PortDeferredItem<ForgeSpawnEggItem> CHAOS_ELEMENTAL_SPAWN_EGG = register(MonsterEntities.CHAOS_ELEMENTAL);
    public static final PortDeferredItem<ForgeSpawnEggItem> DESERT_SLIME_SPAWN_EGG = register(MonsterEntities.DESERT_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANTLION_SWARMER_SPAWN_EGG = register(MonsterEntities.ANTLION_SWARMER);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANTLION_CHARGER_SPAWN_EGG = register(MonsterEntities.ANTLION_CHARGER);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANTLION_LARVA_SPAWN_EGG = register(MonsterEntities.ANTLION_LARVA);
    public static final PortDeferredItem<ForgeSpawnEggItem> GNOME_SPAWN_EGG = register(MonsterEntities.GNOME);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANTLION_SPAWN_EGG = register(MonsterEntities.ANTLION);
    public static final PortDeferredItem<ForgeSpawnEggItem> DESERT_SPIRIT_SPAWN_EGG = register(MonsterEntities.DESERT_SPIRIT);
    public static final PortDeferredItem<ForgeSpawnEggItem> GIANT_ANTLION_SWARMER_SPAWN_EGG = register(MonsterEntities.GIANT_ANTLION_SWARMER);
    public static final PortDeferredItem<ForgeSpawnEggItem> MUMMY_SPAWN_EGG = register(MonsterEntities.MUMMY);
    public static final PortDeferredItem<ForgeSpawnEggItem> DARK_MUMMY_SPAWN_EGG = register(MonsterEntities.DARK_MUMMY);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLOOD_MUMMY_SPAWN_EGG = register(MonsterEntities.BLOOD_MUMMY);
    public static final PortDeferredItem<ForgeSpawnEggItem> LIGHT_MUMMY_SPAWN_EGG = register(MonsterEntities.LIGHT_MUMMY);
    public static final PortDeferredItem<ForgeSpawnEggItem> SAND_POACHER_SPAWN_EGG = register(MonsterEntities.SAND_POACHER);
    public static final PortDeferredItem<ForgeSpawnEggItem> DARK_LAMIA_SPAWN_EGG = register(MonsterEntities.DARK_LAMIA);
    public static final PortDeferredItem<ForgeSpawnEggItem> LIGHT_LAMIA_SPAWN_EGG = register(MonsterEntities.LIGHT_LAMIA);
    public static final PortDeferredItem<ForgeSpawnEggItem> GHOUL_SPAWN_EGG = register(MonsterEntities.GHOUL);
    public static final PortDeferredItem<ForgeSpawnEggItem> BASILISK_SPAWN_EGG = register(MonsterEntities.BASILISK);
    public static final PortDeferredItem<ForgeSpawnEggItem> TAINTED_GHOUL_SPAWN_EGG = register(MonsterEntities.TAINTED_GHOUL);
    public static final PortDeferredItem<ForgeSpawnEggItem> VILE_GHOUL_SPAWN_EGG = register(MonsterEntities.VILE_GHOUL);
    public static final PortDeferredItem<ForgeSpawnEggItem> DREAMER_GHOUL_SPAWN_EGG = register(MonsterEntities.DREAMER_GHOUL);
    public static final PortDeferredItem<ForgeSpawnEggItem> TOMB_CRAWLER_SPAWN_EGG = register(MonsterEntities.TOMB_CRAWLER);
    public static final PortDeferredItem<ForgeSpawnEggItem> JUNGLE_SLIME_SPAWN_EGG = register(MonsterEntities.JUNGLE_SLIME, 0x9ae920, 0xC7AB5E);
    public static final PortDeferredItem<ForgeSpawnEggItem> SPIKED_JUNGLE_SLIME_SPAWN_EGG = register(MonsterEntities.SPIKED_JUNGLE_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> JUNGLE_BAT_SPAWN_EGG = register(MonsterEntities.JUNGLE_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> HORNET_SPAWN_EGG = register(MonsterEntities.HORNET);
    public static final PortDeferredItem<ForgeSpawnEggItem> MOSS_HORNET_SPAWN_EGG = register(MonsterEntities.MOSS_HORNET);
    public static final PortDeferredItem<ForgeSpawnEggItem> JUNGLE_CREEPER_SPAWN_EGG = register(MonsterEntities.JUNGLE_CREEPER);
    public static final PortDeferredItem<ForgeSpawnEggItem> WALL_CREEPER_SPAWN_EGG = register(MonsterEntities.WALL_CREEPER);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLACK_RECLUSE_SPAWN_EGG = register(MonsterEntities.BLACK_RECLUSE);
    public static final PortDeferredItem<ForgeSpawnEggItem> LITTLE_HORNET_SPAWN_EGG = register(MonsterEntities.LITTLE_HORNET);
    public static final PortDeferredItem<ForgeSpawnEggItem> MAN_EATER_SPAWN_EGG = register(MonsterEntities.MAN_EATER);
    public static final PortDeferredItem<ForgeSpawnEggItem> FUNGI_BULB_SPAWN_EGG = register(MonsterEntities.FUNGI_BULB);
    public static final PortDeferredItem<ForgeSpawnEggItem> GIANT_FUNGI_BULB_SPAWN_EGG = register(MonsterEntities.GIANT_FUNGI_BULB);
    public static final PortDeferredItem<ForgeSpawnEggItem> CLINGER_SPAWN_EGG = register(MonsterEntities.CLINGER);
    public static final PortDeferredItem<ForgeSpawnEggItem> TROPIC_SLIME_SPAWN_EGG = register(MonsterEntities.TROPIC_SLIME, 0x73bcf4, 0x7374f4);
    public static final PortDeferredItem<ForgeSpawnEggItem> DERPLING_SPAWN_EGG = register(MonsterEntities.DERPLING);
    public static final PortDeferredItem<ForgeSpawnEggItem> SWEET_SLIME_SPAWN_EGG = register(MonsterEntities.SWEET_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> SNATCHER_SPAWN_EGG = register(MonsterEntities.SNATCHER);
    public static final PortDeferredItem<ForgeSpawnEggItem> GIANT_TORTOISE_SPAWN_EGG = register(MonsterEntities.GIANT_TORTOISE);
    public static final PortDeferredItem<ForgeSpawnEggItem> ICE_TORTOISE_SPAWN_EGG = register(MonsterEntities.ICE_TORTOISE);
    public static final PortDeferredItem<ForgeSpawnEggItem> FIREFLY_SPAWN_EGG = register(CritterEntities.FIREFLY);
    public static final PortDeferredItem<ForgeSpawnEggItem> LIGHTNING_BUG_SPAWN_EGG = register(CritterEntities.LIGHTNING_BUG);
    public static final PortDeferredItem<ForgeSpawnEggItem> TRUFFLE_WORM_SPAWN_EGG = register(CritterEntities.TRUFFLE_WORM);
    public static final PortDeferredItem<ForgeSpawnEggItem> ARMORED_VIKING_SPAWN_EGG = register(MonsterEntities.ARMORED_VIKING);
    public static final PortDeferredItem<ForgeSpawnEggItem> ARMORED_SKELETON_SPAWN_EGG = register(MonsterEntities.ARMORED_SKELETON);
    public static final PortDeferredItem<ForgeSpawnEggItem> ICE_ELEMENTAL_SPAWN_EGG = register(MonsterEntities.ICE_ELEMENTAL);
    public static final PortDeferredItem<ForgeSpawnEggItem> ICY_MERMAN_SPAWN_EGG = register(MonsterEntities.ICY_MERMAN);
    public static final PortDeferredItem<ForgeSpawnEggItem> ICE_GOLEM_SPAWN_EGG = register(MonsterEntities.ICE_GOLEM);
    public static final PortDeferredItem<ForgeSpawnEggItem> ROCK_GOLEM_SPAWN_EGG = register(MonsterEntities.ROCK_GOLEM);
    public static final PortDeferredItem<ForgeSpawnEggItem> ICE_SLIME_SPAWN_EGG = register(MonsterEntities.ICE_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> SPIKED_ICE_SLIME_SPAWN_EGG = register(MonsterEntities.SPIKED_ICE_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> ICE_BAT_SPAWN_EGG = register(MonsterEntities.ICE_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> SNOW_FLINX_SPAWN_EGG = register(MonsterEntities.SNOW_FLINX);
    public static final PortDeferredItem<ForgeSpawnEggItem> UNDEAD_VIKING_SPAWN_EGG = register(MonsterEntities.UNDEAD_VIKING);
    public static final PortDeferredItem<ForgeSpawnEggItem> PURPLE_SLIME_SPAWN_EGG = register(MonsterEntities.PURPLE_SLIME, 0xf334f8, 0xA246BE);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLUE_SLIME_SPAWN_EGG = register(MonsterEntities.BLUE_SLIME, 0x73bcf4, 0x466CBE);
    public static final PortDeferredItem<ForgeSpawnEggItem> GREEN_SLIME_SPAWN_EGG = register(MonsterEntities.GREEN_SLIME, 0xa2f89f, 0x3de838);
    public static final PortDeferredItem<ForgeSpawnEggItem> PINK_SLIME_SPAWN_EGG = register(MonsterEntities.PINK_SLIME, 0xFF87B3, 0xf89fe3);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOLDEN_SLIME_SPAWN_EGG = register(MonsterEntities.GOLDEN_SLIME, 0xfcf8bd, 0xf8e234);
    public static final PortDeferredItem<ForgeSpawnEggItem> DEMON_EYE_SPAWN_EGG = register(MonsterEntities.DEMON_EYE);
    public static final PortDeferredItem<ForgeSpawnEggItem> POSSESS_ARMOR_SPAWN_EGG = register(MonsterEntities.POSSESS_ARMOR);
    public static final PortDeferredItem<ForgeSpawnEggItem> WEREWOLF_SPAWN_EGG = register(MonsterEntities.WEREWOLF);
    public static final PortDeferredItem<ForgeSpawnEggItem> CORRUPT_PENGUIN_SPAWN_EGG = register(MonsterEntities.CORRUPT_PENGUIN);
    public static final PortDeferredItem<ForgeSpawnEggItem> VICIOUS_PENGUIN_SPAWN_EGG = register(MonsterEntities.VICIOUS_PENGUIN);
    public static final PortDeferredItem<ForgeSpawnEggItem> WRAITH_SPAWN_EGG = register(MonsterEntities.WRAITH);
    public static final PortDeferredItem<ForgeSpawnEggItem> SWAMP_SLIME_SPAWN_EGG = register(MonsterEntities.SWAMP_SLIME, 0xa2f89f, 0x3de838);
    public static final PortDeferredItem<ForgeSpawnEggItem> SPIKED_SLIME_SPAWN_EGG = register(MonsterEntities.SPIKED_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> GREEN_DUMPLING_SLIME_SPAWN_EGG = register(MonsterEntities.GREEN_DUMPLING_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> SQUIRREL_SPAWN_EGG = register(CritterEntities.SQUIRREL);
    public static final PortDeferredItem<ForgeSpawnEggItem> RED_SQUIRREL_SPAWN_EGG = register(CritterEntities.RED_SQUIRREL);
    public static final PortDeferredItem<ForgeSpawnEggItem> JEWEL_SQUIRREL_SPAWN_EGG = register(CritterEntities.JEWEL_SQUIRREL);
    public static final PortDeferredItem<ForgeSpawnEggItem> GLOWING_MOOSHROOM_SPAWN_EGG = register(CritterEntities.GLOWING_MOOSHROOM);
    public static final PortDeferredItem<ForgeSpawnEggItem> CLOUD_SHEEP_SPAWN_EGG = register(CritterEntities.CLOUD_SHEEP);
    public static final PortDeferredItem<ForgeSpawnEggItem> CLUCKSHROOM_SPAWN_EGG = register(CritterEntities.CLUCKSHROOM);
    public static final PortDeferredItem<ForgeSpawnEggItem> GLOWING_CLUCKSHROOM_SPAWN_EGG = register(CritterEntities.GLOWING_CLUCKSHROOM);
    public static final PortDeferredItem<ForgeSpawnEggItem> BUNNY_SPAWN_EGG = register(CritterEntities.BUNNY);
    public static final PortDeferredItem<ForgeSpawnEggItem> PENGUIN_SPAWN_EGG = register(CritterEntities.PENGUIN);
    public static final PortDeferredItem<ForgeSpawnEggItem> MYSTIC_FROG_SPAWN_EGG = register(CritterEntities.MYSTIC_FROG);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOLDFISH_SPAWN_EGG = register(CritterEntities.GOLDFISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> JEWEL_BUNNY_SPAWN_EGG = register(CritterEntities.JEWEL_BUNNY);
    public static final PortDeferredItem<ForgeSpawnEggItem> EXPLOSIVE_BUNNY_SPAWN_EGG = register(CritterEntities.EXPLOSIVE_BUNNY);
    public static final PortDeferredItem<ForgeSpawnEggItem> HOSTILE_BUNNY_SPAWN_EGG = register(CritterEntities.HOSTILE_BUNNY);
    public static final PortDeferredItem<ForgeSpawnEggItem> DUCK_SPAWN_EGG = register(CritterEntities.DUCK);
    public static final PortDeferredItem<ForgeSpawnEggItem> BIRD_SPAWN_EGG = register(CritterEntities.BIRD);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLUE_JAY_SPAWN_EGG = register(CritterEntities.BLUE_JAY);
    public static final PortDeferredItem<ForgeSpawnEggItem> CARDINAL_SPAWN_EGG = register(CritterEntities.CARDINAL);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLACK_SLIME_SPAWN_EGG = register(MonsterEntities.BLACK_SLIME, 0x7E7E7E, 0x373535);
    public static final PortDeferredItem<ForgeSpawnEggItem> RED_SLIME_SPAWN_EGG = register(MonsterEntities.RED_SLIME, 0xf83434, 0xA51E1E);
    public static final PortDeferredItem<ForgeSpawnEggItem> YELLOW_SLIME_SPAWN_EGG = register(MonsterEntities.YELLOW_SLIME, 0xf8e234, 0xd19519);
    public static final PortDeferredItem<ForgeSpawnEggItem> CAVE_BAT_SPAWN_EGG = register(MonsterEntities.CAVE_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> GIANT_BAT_SPAWN_EGG = register(MonsterEntities.GIANT_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> GIANT_SHELLY_SPAWN_EGG = register(MonsterEntities.GIANT_SHELLY);
    public static final PortDeferredItem<ForgeSpawnEggItem> CRAWDAD_SPAWN_EGG = register(MonsterEntities.CRAWDAD);
    public static final PortDeferredItem<ForgeSpawnEggItem> GIANT_WORM_SPAWN_EGG = register(MonsterEntities.GIANT_WORM);
    public static final PortDeferredItem<ForgeSpawnEggItem> DIGGER_SPAWN_EGG = register(MonsterEntities.DIGGER);
    public static final PortDeferredItem<ForgeSpawnEggItem> NYMPH_SPAWN_EGG = register(MonsterEntities.NYMPH);
    public static final PortDeferredItem<ForgeSpawnEggItem> GRANITE_ELEMENTAL_SPAWN_EGG = register(MonsterEntities.GRANITE_ELEMENTAL);
    public static final PortDeferredItem<ForgeSpawnEggItem> GRANITE_GOLEM_SPAWN_EGG = register(MonsterEntities.GRANITE_GOLEM);
    public static final PortDeferredItem<ForgeSpawnEggItem> HOPLITE_SPAWN_EGG = register(MonsterEntities.HOPLITE);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANGRY_DANDELION_SPAWN_EGG = register(MonsterEntities.ANGRY_DANDELION);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANGRY_TUMBLER_SPAWN_EGG = register(MonsterEntities.ANGRY_TUMBLER);
    public static final PortDeferredItem<ForgeSpawnEggItem> SAND_SHARK_SPAWN_EGG = register(MonsterEntities.SAND_SHARK);
    public static final PortDeferredItem<ForgeSpawnEggItem> BONE_BITER_SPAWN_EGG = register(MonsterEntities.BONE_BITER);
    public static final PortDeferredItem<ForgeSpawnEggItem> FLESH_REAVER_SPAWN_EGG = register(MonsterEntities.FLESH_REAVER);
    public static final PortDeferredItem<ForgeSpawnEggItem> CRYSTAL_THRESHER_SPAWN_EGG = register(MonsterEntities.CRYSTAL_THRESHER);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANGRY_NIMBUS_SPAWN_EGG = register(MonsterEntities.ANGRY_NIMBUS);
    public static final PortDeferredItem<ForgeSpawnEggItem> METEOR_HEAD_SPAWN_EGG = register(MonsterEntities.METEOR_HEAD);
    public static final PortDeferredItem<ForgeSpawnEggItem> SPORE_BAT_SPAWN_EGG = register(MonsterEntities.SPORE_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> SPORE_SKELETON_SPAWN_EGG = register(MonsterEntities.SPORE_SKELETON);
    public static final PortDeferredItem<ForgeSpawnEggItem> SPORE_ZOMBIE_SPAWN_EGG = register(MonsterEntities.SPORE_ZOMBIE);
    public static final PortDeferredItem<ForgeSpawnEggItem> HAT_SPORE_ZOMBIE_SPAWN_EGG = register(MonsterEntities.HAT_SPORE_ZOMBIE);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANGER_BONES_SPAWN_EGG = register(MonsterEntities.ANGER_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> SHORT_BONES_SPAWN_EGG = register(MonsterEntities.SHORT_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> BIG_BONES_SPAWN_EGG = register(MonsterEntities.BIG_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> BIG_ANGER_BONES_SPAWN_EGG = register(MonsterEntities.BIG_ANGER_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> BIG_MUSCLE_ANGER_BONES_SPAWN_EGG = register(MonsterEntities.BIG_MUSCLE_ANGER_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> BIG_HELMET_ANGER_BONES_SPAWN_EGG = register(MonsterEntities.BIG_HELMET_ANGER_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> CURSED_SKULL_SPAWN_EGG = register(MonsterEntities.CURSED_SKULL);
    public static final PortDeferredItem<ForgeSpawnEggItem> DARK_CASTER_SPAWN_EGG = register(MonsterEntities.DARK_CASTER);
    public static final PortDeferredItem<ForgeSpawnEggItem> WATER_BOLT_MIMIC_SPAWN_EGG = register(MonsterEntities.WATER_BOLT_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> TIM_SPAWN_EGG = register(MonsterEntities.TIM);
    public static final PortDeferredItem<ForgeSpawnEggItem> RUNE_WIZARD_SPAWN_EGG = register(MonsterEntities.RUNE_WIZARD);
    public static final PortDeferredItem<ForgeSpawnEggItem> DOCTOR_BONES_SPAWN_EGG = register(MonsterEntities.DOCTOR_BONES);
    public static final PortDeferredItem<ForgeSpawnEggItem> THE_GROOM_SPAWN_EGG = register(MonsterEntities.THE_GROOM);
    public static final PortDeferredItem<ForgeSpawnEggItem> THE_BRIDE_SPAWN_EGG = register(MonsterEntities.THE_BRIDE);
    public static final PortDeferredItem<ForgeSpawnEggItem> ZOMBIE_MERMAN_SPAWN_EGG = register(MonsterEntities.ZOMBIE_MERMAN);
    public static final PortDeferredItem<ForgeSpawnEggItem> PALADIN_SPAWN_EGG = register(MonsterEntities.PALADIN);
    public static final PortDeferredItem<ForgeSpawnEggItem> BONE_LEE_SPAWN_EGG = register(MonsterEntities.BONE_LEE);
    public static final PortDeferredItem<ForgeSpawnEggItem> NECROMANCER_SPAWN_EGG = register(MonsterEntities.NECROMANCER);
    public static final PortDeferredItem<ForgeSpawnEggItem> DIABOLIST_SPAWN_EGG = register(MonsterEntities.DIABOLIST);
    public static final PortDeferredItem<ForgeSpawnEggItem> RAGGED_CASTER_SPAWN_EGG = register(MonsterEntities.RAGGED_CASTER);
    public static final PortDeferredItem<ForgeSpawnEggItem> DUNGEON_SLIME_SPAWN_EGG = register(MonsterEntities.DUNGEON_SLIME, 0x6d697b, 0x6d697b);
    public static final PortDeferredItem<ForgeSpawnEggItem> DUNGEON_GUARDIAN_SPAWN_EGG = register(BossEntities.DUNGEON_GUARDIAN);
    public static final PortDeferredItem<ForgeSpawnEggItem> FIRE_IMP_SPAWN_EGG = register(MonsterEntities.FIRE_IMP);
    public static final PortDeferredItem<ForgeSpawnEggItem> DEMON_SPAWN_EGG = register(MonsterEntities.DEMON);
    public static final PortDeferredItem<ForgeSpawnEggItem> VOODOO_DEMON_SPAWN_EGG = register(MonsterEntities.VOODOO_DEMON);
    public static final PortDeferredItem<ForgeSpawnEggItem> LAVA_SLIME_SPAWN_EGG = register(MonsterEntities.LAVA_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> HELL_BAT_SPAWN_EGG = register(MonsterEntities.HELL_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> LAVA_BAT_SPAWN_EGG = register(MonsterEntities.LAVA_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> RED_DEVIL_SPAWN_EGG = register(MonsterEntities.RED_DEVIL);
    public static final PortDeferredItem<ForgeSpawnEggItem> ILLUMINANT_BAT_SPAWN_EGG = register(MonsterEntities.ILLUMINANT_BAT);
    public static final PortDeferredItem<ForgeSpawnEggItem> BONE_SERPENT_SPAWN_EGG = register(MonsterEntities.BONE_SERPENT);
    public static final PortDeferredItem<ForgeSpawnEggItem> WITHER_BONE_SERPENT_SPAWN_EGG = register(MonsterEntities.WITHER_BONE_SERPENT);
    public static final PortDeferredItem<ForgeSpawnEggItem> HARPY_SPAWN_EGG = register(MonsterEntities.HARPY);
    public static final PortDeferredItem<ForgeSpawnEggItem> WYVERN_SPAWN_EGG = register(MonsterEntities.WYVERN);
    public static final PortDeferredItem<ForgeSpawnEggItem> ARCH_WYVERN_SPAWN_EGG = register(MonsterEntities.ARCH_WYVERN);
    public static final PortDeferredItem<ForgeSpawnEggItem> FLYING_FISH_SPAWN_EGG = register(MonsterEntities.FLYING_FISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> WOODEN_MIMIC_SPAWN_EGG = register(MonsterEntities.WOODEN_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOLDEN_MIMIC_SPAWN_EGG = register(MonsterEntities.GOLDEN_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> SHADOW_MIMIC_SPAWN_EGG = register(MonsterEntities.SHADOW_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> ICE_MIMIC_SPAWN_EGG = register(MonsterEntities.ICE_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> CRIMSON_MIMIC_SPAWN_EGG = register(MonsterEntities.CRIMSON_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> CORRUPT_MIMIC_SPAWN_EGG = register(MonsterEntities.CORRUPT_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> HALLOWED_MIMIC_SPAWN_EGG = register(MonsterEntities.HALLOWED_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> JUNGLE_MIMIC_SPAWN_EGG = register(MonsterEntities.JUNGLE_MIMIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_SORCERER_SPAWN_EGG = register(MonsterEntities.GOBLIN_SORCERER);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_WARLOCK_SPAWN_EGG = register(MonsterEntities.GOBLIN_WARLOCK);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRATE_DECKHAND_SPAWN_EGG = register(MonsterEntities.PIRATE_DECKHAND);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRATE_DEADEYE_SPAWN_EGG = register(MonsterEntities.PIRATE_DEADEYE);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRATE_CROSSBOWER_SPAWN_EGG = register(MonsterEntities.PIRATE_CROSSBOWER);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRATE_CORSAIR_SPAWN_EGG = register(MonsterEntities.PIRATE_CORSAIR);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRATE_CAPTAIN_SPAWN_EGG = register(MonsterEntities.PIRATE_CAPTAIN);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRATE_PARROT_SPAWN_EGG = register(MonsterEntities.PIRATE_PARROT);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRATES_CURSE_SPAWN_EGG = register(MonsterEntities.PIRATES_CURSE);
    public static final PortDeferredItem<ForgeSpawnEggItem> MARTIAN_PROBE_SPAWN_EGG = register(MonsterEntities.MARTIAN_PROBE);
    public static final PortDeferredItem<ForgeSpawnEggItem> SHADOWFLAME_APPARITION_SPAWN_EGG = register(MonsterEntities.SHADOWFLAME_APPARITION);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_ARCHER_SPAWN_EGG = register(MonsterEntities.GOBLIN_ARCHER);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_PEON_SPAWN_EGG = register(MonsterEntities.GOBLIN_PEON);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_WARRIOR_SPAWN_EGG = register(MonsterEntities.GOBLIN_WARRIOR);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_THIEF_SPAWN_EGG = register(MonsterEntities.GOBLIN_THIEF);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_SCOUT_SPAWN_EGG = register(MonsterEntities.GOBLIN_SCOUT);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANGER_GOBLIN_SPAWN_EGG = register(MonsterEntities.ANGER_GOBLIN);
    public static final PortDeferredItem<ForgeSpawnEggItem> PIRANHA_SPAWN_EGG = register(MonsterEntities.PIRANHA);
    public static final PortDeferredItem<ForgeSpawnEggItem> CORRUPT_GOLDFISH_SPAWN_EGG = register(MonsterEntities.CORRUPT_GOLDFISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> VICIOUS_GOLDFISH_SPAWN_EGG = register(MonsterEntities.VICIOUS_GOLDFISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANGLER_FISH_SPAWN_EGG = register(MonsterEntities.ANGLER_FISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> SHARK_SPAWN_EGG = register(MonsterEntities.SHARK);
    public static final PortDeferredItem<ForgeSpawnEggItem> ARAPAIMA_SPAWN_EGG = register(MonsterEntities.ARAPAIMA);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLUE_JELLYFISH_SPAWN_EGG = register(MonsterEntities.BLUE_JELLYFISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> PINK_JELLYFISH_SPAWN_EGG = register(MonsterEntities.PINK_JELLYFISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> GREEN_JELLYFISH_SPAWN_EGG = register(MonsterEntities.GREEN_JELLYFISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> BLOOD_JELLY_SPAWN_EGG = register(MonsterEntities.BLOOD_JELLY);
    public static final PortDeferredItem<ForgeSpawnEggItem> FUNGO_FISH_SPAWN_EGG = register(MonsterEntities.FUNGO_FISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> WANDERING_EYE_FISH_SPAWN_EGG = register(MonsterEntities.WANDERING_EYE_FISH);
    public static final PortDeferredItem<ForgeSpawnEggItem> CRAB_SPAWN_EGG = register(CritterEntities.CRAB);
    public static final PortDeferredItem<ForgeSpawnEggItem> GLOWING_SNAIL_SPAWN_EGG = register(CritterEntities.GLOWING_SNAIL);
    public static final PortDeferredItem<ForgeSpawnEggItem> GRUBBY_SPAWN_EGG = register(CritterEntities.GRUBBY);
    public static final PortDeferredItem<ForgeSpawnEggItem> MAGGOT_SPAWN_EGG = register(CritterEntities.MAGGOT);
    public static final PortDeferredItem<ForgeSpawnEggItem> MAGMA_SNAIL_SPAWN_EGG = register(CritterEntities.MAGMA_SNAIL);
    public static final PortDeferredItem<ForgeSpawnEggItem> SLUGGY_SPAWN_EGG = register(CritterEntities.SLUGGY);
    public static final PortDeferredItem<ForgeSpawnEggItem> STINKBUG_SPAWN_EGG = register(CritterEntities.STINKBUG);
    public static final PortDeferredItem<ForgeSpawnEggItem> BUGGY_SPAWN_EGG = register(CritterEntities.BUGGY);
    public static final PortDeferredItem<ForgeSpawnEggItem> SNAIL_SPAWN_EGG = register(CritterEntities.SNAIL);
    public static final PortDeferredItem<ForgeSpawnEggItem> BUTTERFLY_SPAWN_EGG = register(CritterEntities.BUTTERFLY);
    public static final PortDeferredItem<ForgeSpawnEggItem> HELL_BUTTERFLY_SPAWN_EGG = register(CritterEntities.HELL_BUTTERFLY);
    public static final PortDeferredItem<ForgeSpawnEggItem> PRISMATIC_LACEWING_SPAWN_EGG = register(CritterEntities.PRISMATIC_LACEWING);
    public static final PortDeferredItem<ForgeSpawnEggItem> DRAGONFLY_SPAWN_EGG = register(CritterEntities.DRAGONFLY);
    public static final PortDeferredItem<ForgeSpawnEggItem> FAIRY_SPAWN_EGG = register(CritterEntities.FAIRY);
    public static final PortDeferredItem<ForgeSpawnEggItem> FEALING_SPAWN_EGG = register(CritterEntities.FEALING);
    public static final PortDeferredItem<ForgeSpawnEggItem> GRASSHOPPER_SPAWN_EGG = register(CritterEntities.GRASSHOPPER);
    public static final PortDeferredItem<ForgeSpawnEggItem> LADYBUG_SPAWN_EGG = register(CritterEntities.LADYBUG);
    public static final PortDeferredItem<ForgeSpawnEggItem> SCORPION_SPAWN_EGG = register(CritterEntities.SCORPION);
    public static final PortDeferredItem<ForgeSpawnEggItem> WORM_SPAWN_EGG = register(CritterEntities.WORM);
    public static final PortDeferredItem<ForgeSpawnEggItem> GUIDE_SPAWN_EGG = register(NpcEntities.GUIDE);
    public static final PortDeferredItem<ForgeSpawnEggItem> DEMOLITIONIST_SPAWN_EGG = register(NpcEntities.DEMOLITIONIST);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOBLIN_TINKERER_SPAWN_EGG = register(NpcEntities.GOBLIN_TINKERER);
    public static final PortDeferredItem<ForgeSpawnEggItem> ARMS_DEALER_SPAWN_EGG = register(NpcEntities.ARMS_DEALER);
    public static final PortDeferredItem<ForgeSpawnEggItem> NURSE_SPAWN_EGG = register(NpcEntities.NURSE);
    public static final PortDeferredItem<ForgeSpawnEggItem> MERCHANT_SPAWN_EGG = register(NpcEntities.MERCHANT);
    public static final PortDeferredItem<ForgeSpawnEggItem> PAINTER_SPAWN_EGG = register(NpcEntities.PAINTER);
    public static final PortDeferredItem<ForgeSpawnEggItem> DRYAD_SPAWN_EGG = register(NpcEntities.DRYAD);
    public static final PortDeferredItem<ForgeSpawnEggItem> DYE_TRADER_SPAWN_EGG = register(NpcEntities.DYE_TRADER);
    public static final PortDeferredItem<ForgeSpawnEggItem> ANGLER_SPAWN_EGG = register(NpcEntities.ANGLER);
    public static final PortDeferredItem<ForgeSpawnEggItem> FEMALE_ANGLER_SPAWN_EGG = register(NpcEntities.FEMALE_ANGLER);
    public static final PortDeferredItem<ForgeSpawnEggItem> OLD_MAN_SPAWN_EGG = register(NpcEntities.OLD_MAN);
    public static final PortDeferredItem<ForgeSpawnEggItem> MECHANIC_SPAWN_EGG = register(NpcEntities.MECHANIC);
    public static final PortDeferredItem<ForgeSpawnEggItem> TRAVELING_MERCHANT_SPAWN_EGG = register(NpcEntities.TRAVELING_MERCHANT);
    public static final PortDeferredItem<ForgeSpawnEggItem> WITCH_DOCTOR_SPAWN_EGG = register(NpcEntities.WITCH_DOCTOR);
    public static final PortDeferredItem<ForgeSpawnEggItem> PARTY_GIRL_SPAWN_EGG = register(NpcEntities.PARTY_GIRL);
    public static final PortDeferredItem<ForgeSpawnEggItem> CLOTHIER_SPAWN_EGG = register(NpcEntities.CLOTHIER);
    public static final PortDeferredItem<ForgeSpawnEggItem> STYLIST_SPAWN_EGG = register(NpcEntities.STYLIST);
    public static final PortDeferredItem<ForgeSpawnEggItem> TAX_COLLECTOR_SPAWN_EGG = register(NpcEntities.TAX_COLLECTOR);
    public static final PortDeferredItem<ForgeSpawnEggItem> ZOOLOGIST_SPAWN_EGG = register(NpcEntities.ZOOLOGIST);
    public static final PortDeferredItem<ForgeSpawnEggItem> TRUFFLE_SPAWN_EGG = register(NpcEntities.TRUFFLE);
    public static final PortDeferredItem<ForgeSpawnEggItem> WIZARD_SPAWN_EGG = register(NpcEntities.WIZARD);
    public static final PortDeferredItem<ForgeSpawnEggItem> STEAMPUNKER_SPAWN_EGG = register(NpcEntities.STEAMPUNKER);
    public static final PortDeferredItem<ForgeSpawnEggItem> CYBORG_SPAWN_EGG = register(NpcEntities.CYBORG);
    public static final PortDeferredItem<ForgeSpawnEggItem> GOLFER_SPAWN_EGG = register(NpcEntities.GOLFER);
    public static final PortDeferredItem<ForgeSpawnEggItem> NERDY_SLIME_SPAWN_EGG = register(NpcEntities.NERDY_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> COOL_SLIME_SPAWN_EGG = register(NpcEntities.COOL_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> ELDER_SLIME_SPAWN_EGG = register(NpcEntities.ELDER_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> CLUMSY_SLIME_SPAWN_EGG = register(NpcEntities.CLUMSY_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> DIVA_SLIME_SPAWN_EGG = register(NpcEntities.DIVA_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> SURLY_SLIME_SPAWN_EGG = register(NpcEntities.SURLY_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> MYSTIC_SLIME_SPAWN_EGG = register(NpcEntities.MYSTIC_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> SQUIRE_SLIME_SPAWN_EGG = register(NpcEntities.SQUIRE_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> SKELETON_MERCHANT_SPAWN_EGG = register(NpcEntities.SKELETON_MERCHANT);
    public static final PortDeferredItem<ForgeSpawnEggItem> KING_SLIME_SPAWN_EGG = register(BossEntities.KING_SLIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> EYE_OF_CTHULHU_SPAWN_EGG = register(BossEntities.EYE_OF_CTHULHU);
    public static final PortDeferredItem<ForgeSpawnEggItem> EATER_OF_WORLDS_SPAWN_EGG = register(BossEntities.EATER_OF_WORLDS);
    public static final PortDeferredItem<ForgeSpawnEggItem> BRAIN_OF_CTHULHU_SPAWN_EGG = register(BossEntities.BRAIN_OF_CTHULHU);
    public static final PortDeferredItem<ForgeSpawnEggItem> QUEEN_BEE_SPAWN_EGG = register(BossEntities.QUEEN_BEE);
    public static final PortDeferredItem<ForgeSpawnEggItem> SKELETRON_SPAWN_EGG = register(BossEntities.SKELETRON);
    public static final PortDeferredItem<ForgeSpawnEggItem> DEERCLOPS_SPAWN_EGG = register(BossEntities.DEERCLOPS);
    public static final PortDeferredItem<ForgeSpawnEggItem> WALL_OF_FLESH_SPAWN_EGG = register(BossEntities.WALL_OF_FLESH);
    public static final PortDeferredItem<ForgeSpawnEggItem> HILL_OF_FLESH_SPAWN_EGG = register(BossEntities.HILL_OF_FLESH);
    public static final PortDeferredItem<ForgeSpawnEggItem> PRIME_ENDER_DRAGON_SPAWN_EGG = register(BossEntities.PRIME_ENDER_DRAGON);
    public static final PortDeferredItem<ForgeSpawnEggItem> RETINAZER_SPAWN_EGG = register(BossEntities.RETINAZER);
    public static final PortDeferredItem<ForgeSpawnEggItem> SPAZMATISM_SPAWN_EGG = register(BossEntities.SPAZMATISM);
    public static final PortDeferredItem<ForgeSpawnEggItem> THE_TWINS_SPAWN_EGG = register(BossEntities.THE_TWINS);
    public static final PortDeferredItem<ForgeSpawnEggItem> SKELETRON_PRIME_SPAWN_EGG = register(BossEntities.SKELETRON_PRIME);
    public static final PortDeferredItem<ForgeSpawnEggItem> THE_DESTROYER_SPAWN_EGG = register(BossEntities.THE_DESTROYER);
    public static final PortDeferredItem<ForgeSpawnEggItem> PLANTERA_SPAWN_EGG = register(BossEntities.PLANTERA);
    public static final PortDeferredItem<ForgeSpawnEggItem> LUNATIC_CULTIST_SPAWN_EGG = register(BossEntities.LUNATIC_CULTIST);
    public static final PortDeferredItem<ForgeSpawnEggItem> PHANTASM_DRAGON_SPAWN_EGG = register(BossEntities.PHANTASM_DRAGON);

    public static void init() {}

    private static PortDeferredItem<ForgeSpawnEggItem> register(RegistryObject<? extends EntityType<? extends Mob>> type, int bc, int hc) {
        return ITEMS.register(type.getId().getPath() + "_spawn_egg", () -> new ForgeSpawnEggItem(type, bc, hc, new Item.Properties()));
    }

    private static PortDeferredItem<ForgeSpawnEggItem> register(RegistryObject<? extends EntityType<? extends Mob>> type) {
        return register(type, 0xFFFFFF, 0xFFFFFF);
    }

    private SpawnEggItems() {}
}
